// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMMcNCNyNGyCeB2F2hDV_mwNboZac2TPg',
    appId: '1:547141268440:web:04e54bf83597d8d56db8ad',
    messagingSenderId: '547141268440',
    projectId: 'todolistapp-8e7a1',
    authDomain: 'todolistapp-8e7a1.firebaseapp.com',
    storageBucket: 'todolistapp-8e7a1.firebasestorage.app',
    measurementId: 'G-4KMYGV70GX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzUzK-kpVp5z0R9FKEScPajYErIX_lSL4',
    appId: '1:547141268440:android:5b70f7c6b3e1da776db8ad',
    messagingSenderId: '547141268440',
    projectId: 'todolistapp-8e7a1',
    storageBucket: 'todolistapp-8e7a1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_3zG8zgXSQM479tM0AOPuIujKjKUua6E',
    appId: '1:547141268440:ios:005423e2429a342d6db8ad',
    messagingSenderId: '547141268440',
    projectId: 'todolistapp-8e7a1',
    storageBucket: 'todolistapp-8e7a1.firebasestorage.app',
    iosBundleId: 'com.example.todolistFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_3zG8zgXSQM479tM0AOPuIujKjKUua6E',
    appId: '1:547141268440:ios:005423e2429a342d6db8ad',
    messagingSenderId: '547141268440',
    projectId: 'todolistapp-8e7a1',
    storageBucket: 'todolistapp-8e7a1.firebasestorage.app',
    iosBundleId: 'com.example.todolistFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMMcNCNyNGyCeB2F2hDV_mwNboZac2TPg',
    appId: '1:547141268440:web:bbfef1a4324d2b586db8ad',
    messagingSenderId: '547141268440',
    projectId: 'todolistapp-8e7a1',
    authDomain: 'todolistapp-8e7a1.firebaseapp.com',
    storageBucket: 'todolistapp-8e7a1.firebasestorage.app',
    measurementId: 'G-TCF9R1GPMZ',
  );
}
